[workspace]
members = ["homunculus", "hom"]
resolver = "2"

[workspace.package]
version = "0.3.1"
edition = "2021"

[workspace.dependencies]
glam = { version = "0.24", features = ["serde"] }

[patch.crates-io]
homunculus = { path = "./homunculus" }
