[workspace]
members = ["homunculus", "hom"]
resolver = "2"

[workspace.package]
version = "0.4.0"
edition = "2021"

[workspace.dependencies]
glam = { version = "0.24", features = ["serde"] }
serde = { version = "1", features = ["derive"] }

[patch.crates-io]
homunculus = { path = "./homunculus" }
