[package]
name = "homunculus"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1"
glam = { version = "0.20", features = ["serde"] }
muon-rs = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_repr = "0.1"
